name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Change to root project directory. 
      run: ls
      
    #- name: Build webassembly binary. 
    #  run: make TYPE=release
